# Generated by Django 5.1.3 on 2024-12-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0002_dish_restaurant_delete_restaurants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="photo",
            field=models.ImageField(upload_to="dish_images"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="dishes",
            field=models.ManyToManyField(
                related_name="restaurants", to="Restaurants.dish"
            ),
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours_list",
                        to="Restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
