# Generated by Django 5.1.3 on 2024-12-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0003_alter_dish_available_alter_dish_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="photo",
            field=models.ImageField(
                default="showa_default_pic.jpg", upload_to="dish_images"
            ),
        ),
    ]
