# Generated by Django 5.1.3 on 2024-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0004_alter_dish_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="photo",
            field=models.ImageField(
                blank=True, default="showa_default_pic.jpg", upload_to="dish_images"
            ),
        ),
    ]
