# Generated by Django 5.1.3 on 2024-12-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0005_alter_dish_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="showa_default_pic.jpg",
                null=True,
                upload_to="dish_images",
            ),
        ),
    ]
