# Generated by Django 5.1.3 on 2024-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0006_alter_dish_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish", name="price", field=models.IntegerField(default=200),
        ),
    ]
