# Generated by Django 5.1.3 on 2024-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0007_dish_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.TextField(default="lagos"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
