# Generated by Django 5.1.3 on 2024-12-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurants", "0007_dish_price"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="dishes",
            field=models.ManyToManyField(related_name="dishes", to="Restaurants.dish"),
        ),
    ]
